/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-11 07:11:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import org.apache.tomcat.jni.Local;
import kr.ac.kopo.Util;
import java.util.Calendar;

public final class event_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.22.jar", Long.valueOf(1665220669260L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/spring-webmvc-5.3.22.jar!/META-INF/spring-form.tld", Long.valueOf(1657755656000L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1665220674434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.ac.kopo.Util");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("org.apache.tomcat.jni.Local");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenLite.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/easing/EasePack.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/plugins/CSSPlugin.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"https://tistory4.daumcdn.net/tistory/3134841/skin/images/confetti_v2.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./style/css/main2.css\" />\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b3a7369db8.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("		@font-face { font-family: 'GmarketSansMedium'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansMedium.woff') format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write("		@font-face {\r\n");
      out.write("		    font-family: 'InfinitySans-RegularA1';\r\n");
      out.write("		    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/InfinitySans-RegularA1.woff') format('woff');\r\n");
      out.write("		    font-weight: normal;\r\n");
      out.write("		    font-style: normal;\r\n");
      out.write("			}\r\n");
      out.write("		#wrap{   position: relative; overflow: hidden;}\r\n");
      out.write("		#wrap #gameContainer{width:508px; height:671px; text-align: center; position: relative;margin:0px auto;}\r\n");
      out.write("		#wrap #gameContainer h1{}\r\n");
      out.write("		#wrap #gameContainer .obj{position: absolute;}\r\n");
      out.write("		#wrap #gameContainer .board_start{  \r\n");
      out.write("		    padding: 10px;\r\n");
      out.write("		    background: #f00;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    vertical-align: middle; \r\n");
      out.write("		  	line-height: 100px; \r\n");
      out.write("		    color: #fff474;   \r\n");
      out.write("		    background: #000;\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    vertical-align: middle;\r\n");
      out.write("		    font-weight: bold;\r\n");
      out.write("		position:absolute; left:195px; top:240px;z-index:9; width:120px; border-radius:100px;}\r\n");
      out.write("		#wrap #gameContainer .board_start\r\n");
      out.write("		img{width:100%;}\r\n");
      out.write("		#wrap #gameContainer .board_bg{width:508px; height:508px; top:40px; left:0px; z-index: 2;}\r\n");
      out.write("		#wrap #gameContainer .board_bg img{width:100%;}\r\n");
      out.write("		#wrap #gameContainer .board_on{width:550px; height:550px; top:30px; left:-20px; z-index: 3; background-image: url('./image/img/circle_bg.png');    background-size: 551px;\r\n");
      out.write("		}\r\n");
      out.write("		#wrap #gameContainer .board_on img{position:absolute; width:155px;top:50px; height:100px;}\r\n");
      out.write("		#wrap #gameContainer .board_on img:nth-child(1){    left: 40px;  transform: rotate( -60deg );  top: 133px;}\r\n");
      out.write("		#wrap #gameContainer .board_on img:nth-child(2){left: 38px;  transform: rotate( -113deg );  top: 316px;  }\r\n");
      out.write("		#wrap #gameContainer .board_on img:nth-child(3){  left: 198px;  top: 409px; transform: rotate(-180deg);}  \r\n");
      out.write("		#wrap #gameContainer .board_on img:nth-child(4){left: 351px; top: 315px;  transform: rotate(-245deg);}\r\n");
      out.write("		#wrap #gameContainer .board_on img:nth-child(5){ left: 353px;  top: 137px;  transform: rotate(-292deg);   }\r\n");
      out.write("		#wrap #gameContainer .board_on img:nth-child(6){  left: 197px;  top: 35px;  transform: rotate(5deg); }  \r\n");
      out.write("		\r\n");
      out.write("		#wrap #gameContainer .obj.board_arrow{width:90px; height:105px; top:0px; left:195px; z-index: 5;}\r\n");
      out.write("		#wrap #gameContainer .char1{width:259px; height:246px; top:400px; left:90px; z-index: 1;}\r\n");
      out.write("		#wrap #gameContainer .char2{width:175px; height:198px; top:449px; left:600px; z-index: 1;}\r\n");
      out.write("		#wrap #gameContainer .char3{width:112px; height:108px; top:540px; left:550px; z-index: 3;}\r\n");
      out.write("		#wrap #gameContainer .txt1{width:420px; height:30px; bottom:20px; left:260px; z-index: 3;}\r\n");
      out.write("		\r\n");
      out.write("		.popup {display: none; position: fixed; left: 50%; z-index: 99999; text-align: center; background:#fff; font-size:20px; color:#000;}\r\n");
      out.write("		#fade {display: none;background: #000;position: fixed;left: 0;top: 0;width: 100%;height: 100%;opacity: .60;z-index: 9999;}\r\n");
      out.write("		#popup_gift{width:495px; height:450px; top:210px; border-radius: 10px;}\r\n");
      out.write("		#popup_gift .lottery_present {text-align:center;}\r\n");
      out.write("		#popup_gift .lottery_present img{ display:block; margin: 35px auto 00px;     height: 230px; width: 400px;}\r\n");
      out.write("		\r\n");
      out.write("		#popup_fail{width:475px; height:505px; top:120px;}\r\n");
      out.write("		.popup  .close{ display:inline-block; width:150px; hegiht:50px; line-height:50px; color:#fff; background:#333; margin: 30px 0 0;} \r\n");
      out.write("		canvas{z-index:10;pointer-events: none;position: fixed;top: 0;transform: scale(1.1);}\r\n");
      out.write("		\r\n");
      out.write("		#notice {\r\n");
      out.write("			font-weight: normal;\r\n");
      out.write("			font-size: 20px;\r\n");
      out.write("			margin-bottom: 10px;\r\n");
      out.write("		}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" 	<header>\r\n");
      out.write("   		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<main class=\"hana__main-wrap\" style=\"margin-top: 110px;\">\r\n");
      out.write("		<img src = \"/image/img/event.png\" style=\"width: 1707px; height: 815px; position:absolute; ; z-index: 1;\" >\r\n");
      out.write("		<img src = \"/image/img/lucky.png\" style=\"z-index: 2;  position:relative; width: 350px; margin-top: 35px; margin-left: 655px;\">\r\n");
      out.write("		<div id=\"wrap\" style=\"position: relative; z-index: 2; height: 600px; margin-left: -50px;\" align=\"center\">\r\n");
      out.write("					<img src = \"/image/img/tri.png\" style=\"z-index: 4;  position:absolute; width: 30px; height: 40px; top: 30px; left: 865px;\">\r\n");
      out.write("			<div id=\"gameContainer\">  \r\n");
      out.write("		        <div class=\"board_start join\" style=\"font-size: 30px; font-family: 'InfinitySans-RegularA1';\">START</div>\r\n");
      out.write("		        <div class=\"board_on obj\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("			<div id=\"popup_gift\" class=\"popup\">\r\n");
      out.write("			    <div class=\"lottery_present\"></div>\r\n");
      out.write("	        	<a href=\"javascript:;\" class=\"close\">닫기 </a>\r\n");
      out.write("			</div>\r\n");
      out.write("		<div class=\"buttonContainer\">\r\n");
      out.write("			<button class=\"canvasBtn\" id=\"stopButton\">Stop Confetti</button>\r\n");
      out.write("			<button class=\"canvasBtn\" id=\"startButton\">Drop Confetti</button>	\r\n");
      out.write("		</div>\r\n");
      out.write("		<canvas id=\"canvas\"></canvas>\r\n");
      out.write("		<div style=\"position: relative; height: 200px; background-color: #f9f3f3\">\r\n");
      out.write("			<div class=\"container\" style=\"width: 80%; margin-left: 400px; margin-right: 400px; padding-top: 25px;\">\r\n");
      out.write("				<div style=\"display: inline-block;\"><img src=\"/image/img/notice.png\" style=\"width: 60px; margin-bottom: 30px;\"></div>\r\n");
      out.write("				<a style=\"font-size: 25px; font-weight: bold; position: relative; bottom: 50px; left: 15px;\">공지사항</a>\r\n");
      out.write("				<div style=\"margin-top: 15px; display: inline-block; margin-left: 70px;\">\r\n");
      out.write("					<h5 id=\"notice\"> 	- 본 이벤트는 ID당 1회 참여 가능합니다.</h5>\r\n");
      out.write("					<h5 id=\"notice\">	- 본 이벤트는 제휴적금에 가입한 회원만 참여 가능합니다. </h5>\r\n");
      out.write("					<h5 id=\"notice\">	- 이벤트로 수령하신 쿠폰으로 구매한 상품은 환불/연장이 불가합니다. </h5>\r\n");
      out.write("					<h5 id=\"notice\">	- 본 이벤트는 사정에 따라 예고없이 변동되거나 종료될 수 있습니다. </h5>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	  var gift;\r\n");
      out.write("	       var  present =[ 1,2,3 , 4,5,6 ]\r\n");
      out.write("\r\n");
      out.write("	  iniGame = function(num){\r\n");
      out.write("	    gift = num;\r\n");
      out.write("	    TweenLite.killTweensOf($(\".board_on\"));\r\n");
      out.write("	    TweenLite.to($(\".board_on\"), 0, {css:{rotation:rotationPos[gift]}});\r\n");
      out.write("	    TweenLite.from($(\".board_on\"),5, {css:{rotation:-3000}, onComplete:endGame, ease:Sine.easeOut});\r\n");
      out.write("	               console.log(\"gift 숫자 : \"+ (gift +1) +\"rotationPos\" + rotationPos );\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  var rotationPos = new Array(60,120,180,240,300,360);\r\n");
      out.write("\r\n");
      out.write("	  TweenLite.to($(\".board_on\"), 360, {css:{rotation:-4000}, ease: Linear.easeNone});\r\n");
      out.write("	  function endGame(){\r\n");
      out.write("	              var  copImg= \"./image/img/coupon\"+( gift +1) + \".png\";\r\n");
      out.write("	                console.log(\"이미지 : \" + copImg );\r\n");
      out.write("\r\n");
      out.write("				  $(\"#startButton\").trigger(\"click\");\r\n");
      out.write("				  	setTimeout(function(){\r\n");
      out.write("				  		$(\"#stopButton\").trigger(\"click\");\r\n");
      out.write("				  	}, 3000);\r\n");
      out.write("	                     $(\"#popup_gift .lottery_present\" ).html('당첨을 축하드립니다!! <br><br>' +  '마이페이지 > 내정보 > 쿠폰함에서 확인해주세요');\r\n");
      out.write("	                     \r\n");
      out.write("	                          $( '<img  src=\"' + copImg+ '\" />' ).prependTo(\"#popup_gift .lottery_present\");\r\n");
      out.write("	  setTimeout(function() {openPopup(\"popup_gift\"); }, 1000);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	  $(\".uoc-icon\").on('click', function(){\r\n");
      out.write("		  endGame();\r\n");
      out.write("	  }); \r\n");
      out.write("\r\n");
      out.write("	  $(\".popup .btn\").on(\"click\",function(){\r\n");
      out.write("	    location.reload();\r\n");
      out.write("	  });\r\n");
      out.write("	  function openPopup(id) {\r\n");
      out.write("	    closePopup();\r\n");
      out.write("	    $('.popup').slideUp(0);\r\n");
      out.write("	    var popupid = id\r\n");
      out.write("	    $('body').append('<div id=\"fade\"></div>');\r\n");
      out.write("	    $('#fade').css({\r\n");
      out.write("	    'filter' : 'alpha(opacity=60)'\r\n");
      out.write("	    }).fadeIn(300);\r\n");
      out.write("	    var popuptopmargin = ($('#' + popupid).height()) / 2;\r\n");
      out.write("	    var popupleftmargin = ($('#' + popupid).width()) / 2;\r\n");
      out.write("	    $('#' + popupid).css({\r\n");
      out.write("	      'margin-left' : -popupleftmargin\r\n");
      out.write("	    });\r\n");
      out.write("	    $('#' + popupid).slideDown(500);\r\n");
      out.write("	  }\r\n");
      out.write("	  function closePopup() {\r\n");
      out.write("	    $('#fade').fadeOut(300, function() {\r\n");
      out.write("	      // $(\".player\").html('');\r\n");
      out.write("	    });\r\n");
      out.write("	    $('.popup').slideUp(400);\r\n");
      out.write("	    return false\r\n");
      out.write("	  }\r\n");
      out.write("	  $(\".close\").click(closePopup);\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("	  var clicked  =0;\r\n");
      out.write("	  for(i=1; i<7; i++){\r\n");
      out.write("	  \r\n");
      out.write("	    var  pictures = \"./image/img/coupon\"+ i  + \".png\";\r\n");
      out.write("	    $(\".board_on\").append('<img  src=\"' + pictures + '\" />');\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  $(\".join\").on(\"mousedown\",function(){\r\n");
      out.write("	    if( clicked <= 0){    iniGame(Math.floor(Math.random() *6));    }\r\n");
      out.write("	    else  if( clicked >=1 ){    event.preventDefault(); \r\n");
      out.write("	    Swal.fire({\r\n");
      out.write("	    	  icon: 'info',\r\n");
      out.write("	    	  text: '이미 이벤트에 참여하셨습니다.',\r\n");
      out.write("	    	 \r\n");
      out.write("	    	}) }\r\n");
      out.write("	    clicked ++\r\n");
      out.write("	  });\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
