/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-11 01:56:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.ac.kopo.Util;
import java.util.Calendar;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.22.jar", Long.valueOf(1665220669260L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/spring-webmvc-5.3.22.jar!/META-INF/spring-form.tld", Long.valueOf(1657755656000L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1665220674434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.ac.kopo.Util");
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Calendar cal = Calendar.getInstance();

	int calMonth = cal.get(Calendar.MONTH)+1;

	session.setAttribute("tYear", "" + Calendar.YEAR);
	session.setAttribute("tMonth", "" + calMonth);
	session.setAttribute("tDay", "" + cal.get(Calendar.DATE));

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\"/>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/image/img/apple-icon.png\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"/image/img/favicon.png\">\r\n");
      out.write("  <title>\r\n");
      out.write("    detail\r\n");
      out.write("  </title>\r\n");
      out.write("  <!--     Fonts and icons     -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Nucleo Icons -->\r\n");
      out.write("  <link href=\"/style/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"/style/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/42d5adcbca.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link href=\"/style/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- CSS Files -->\r\n");
      out.write("  <link id=\"pagestyle\" href=\"/style/css/argon-dashboard.css?v=2.0.4\" rel=\"stylesheet\" />\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/b3a7369db8.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("	.bg-gradient-primary{\r\n");
      out.write("		background-image: linear-gradient(30deg, rgb(9,154,150) 0%, #44bdba 100%);\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"g-sidenav-show   bg-gray-100\">\r\n");
 
String year = request.getParameter("year");
String month = request.getParameter("month");

year = Util.getStringNowYear();
month = Util.getStringNowMonth();

      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /WEB-INF/jsp/admin/detail.jsp(60,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("year");
        // /WEB-INF/jsp/admin/detail.jsp(60,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(year);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /WEB-INF/jsp/admin/detail.jsp(61,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("month");
        // /WEB-INF/jsp/admin/detail.jsp(61,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(month);
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("\r\n");
      out.write("  <div class=\"min-height-300 bg-primary position-absolute w-100\" style=\"background-color: rgb(9,154,150) !important\"></div>\r\n");
      out.write("  <aside class=\"sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 \" id=\"sidenav-main\">\r\n");
      out.write("    <div class=\"sidenav-header\">\r\n");
      out.write("      <i class=\"fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none\" aria-hidden=\"true\" id=\"iconSidenav\"></i>\r\n");
      out.write("      <a class=\"navbar-brand m-0\" href=\" https://demos.creative-tim.com/argon-dashboard/pages/dashboard.html \" target=\"_blank\">\r\n");
      out.write("        <img src=\"/image/logo/logo2.png\" class=\"navbar-brand-img h-100\" alt=\"main_logo\">\r\n");
      out.write("        <span class=\"ms-1 font-weight-bold\">하나챌린지</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr class=\"horizontal dark mt-0\">\r\n");
      out.write("    <div class=\"collapse navbar-collapse  w-auto \" id=\"sidenav-collapse-main\">\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" href=\"./pages/dashboard.html\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-tv-2 text-primary text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">대시보드</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/productAdmin\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-app text-warning text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\" style=\"color:#344767 !important; font-weight: bold;\">상품</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/email\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni fa-regular fa-envelope text-success text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\" style=\"color:#344767 !important; font-weight: bold;\">메일</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"./pages/billing.html\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-collection text-info text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\" style=\"color:#344767 !important; font-weight: bold;\">쿠폰</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("       \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sidenav-footer mx-3 \">\r\n");
      out.write("      <div class=\"card card-plain shadow-none\" id=\"sidenavCard\">\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <main class=\"main-content position-relative border-radius-lg \">\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl \" id=\"navbarBlur\" data-scroll=\"false\">\r\n");
      out.write("      <div class=\"container-fluid py-1 px-3\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("          <ol class=\"breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5\">\r\n");
      out.write("            <li class=\"breadcrumb-item text-sm\"><a class=\"opacity-5 text-white\" href=\"javascript:;\">Pages</a></li>\r\n");
      out.write("            <li class=\"breadcrumb-item text-sm text-white active\" aria-current=\"page\">Dashboard</li>\r\n");
      out.write("          </ol>\r\n");
      out.write("          <h4 class=\"font-weight-bolder text-white mb-0\" style=\"position: relative; top: 35px;\">소비자 선호 브랜드 TOP4</h4>\r\n");
      out.write("          <h6 style=\"position: relative;top:35px; color: #555;\">");
      out.print(year);
      out.write('-');
      out.print(month);
      out.write(" 기준</h6>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4\" id=\"navbar\">\r\n");
      out.write("          <div class=\"ms-md-auto pe-md-3 d-flex align-items-center\">\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("              <span class=\"input-group-text text-body\"><i class=\"fas fa-search\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"navbar-nav  justify-content-end\">\r\n");
      out.write("            <li class=\"nav-item d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white font-weight-bold px-0\">\r\n");
      out.write("                <i class=\"fa fa-user me-sm-1\"></i>\r\n");
      out.write("                \r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item d-xl-none ps-3 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\" id=\"iconNavbarSidenav\">\r\n");
      out.write("                <div class=\"sidenav-toggler-inner\">\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item px-3 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\">\r\n");
      out.write("                <i class=\"fa fa-cog fixed-plugin-button-nav cursor-pointer\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown pe-2 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\" id=\"dropdownMenuButton\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fa fa-bell cursor-pointer\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                <li class=\"mb-2\">\r\n");
      out.write("                  <a class=\"dropdown-item border-radius-md\" href=\"javascript:;\">\r\n");
      out.write("                    <div class=\"d-flex py-1\">\r\n");
      out.write("                      <div class=\"my-auto\">\r\n");
      out.write("                        <img src=\"/image/img/team-2.jpg\" class=\"avatar avatar-sm  me-3 \">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex flex-column justify-content-center\">\r\n");
      out.write("                        <h6 class=\"text-sm font-weight-normal mb-1\">\r\n");
      out.write("                          <span class=\"font-weight-bold\">New message</span> from Laur\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        <p class=\"text-xs text-secondary mb-0\">\r\n");
      out.write("                          <i class=\"fa fa-clock me-1\"></i>\r\n");
      out.write("                          13 minutes ago\r\n");
      out.write("                        </p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"mb-2\">\r\n");
      out.write("                  <a class=\"dropdown-item border-radius-md\" href=\"javascript:;\">\r\n");
      out.write("                    <div class=\"d-flex py-1\">\r\n");
      out.write("                      <div class=\"my-auto\">\r\n");
      out.write("                        <img src=\"/image/img/small-logos/logo-spotify.svg\" class=\"avatar avatar-sm bg-gradient-dark  me-3 \">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex flex-column justify-content-center\">\r\n");
      out.write("                        <h6 class=\"text-sm font-weight-normal mb-1\">\r\n");
      out.write("                          <span class=\"font-weight-bold\">New album</span> by Travis Scott\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        <p class=\"text-xs text-secondary mb-0\">\r\n");
      out.write("                          <i class=\"fa fa-clock me-1\"></i>\r\n");
      out.write("                          1 day\r\n");
      out.write("                        </p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item border-radius-md\" href=\"javascript:;\">\r\n");
      out.write("                    <div class=\"d-flex py-1\">\r\n");
      out.write("                      <div class=\"avatar avatar-sm bg-gradient-secondary  me-3  my-auto\">\r\n");
      out.write("                        <svg width=\"12px\" height=\"12px\" viewBox=\"0 0 43 36\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n");
      out.write("                          <title>credit-card</title>\r\n");
      out.write("                          <g stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("                            <g transform=\"translate(-2169.000000, -745.000000)\" fill=\"#FFFFFF\" fill-rule=\"nonzero\">\r\n");
      out.write("                              <g transform=\"translate(1716.000000, 291.000000)\">\r\n");
      out.write("                                <g transform=\"translate(453.000000, 454.000000)\">\r\n");
      out.write("                                  <path class=\"color-background\" d=\"M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z\" opacity=\"0.593633743\"></path>\r\n");
      out.write("                                  <path class=\"color-background\" d=\"M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z\"></path>\r\n");
      out.write("                                </g>\r\n");
      out.write("                              </g>\r\n");
      out.write("                            </g>\r\n");
      out.write("                          </g>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex flex-column justify-content-center\">\r\n");
      out.write("                        <h6 class=\"text-sm font-weight-normal mb-1\">\r\n");
      out.write("                          Payment successfully completed\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        <p class=\"text-xs text-secondary mb-0\">\r\n");
      out.write("                          <i class=\"fa fa-clock me-1\"></i>\r\n");
      out.write("                          2 days\r\n");
      out.write("                        </p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- End Navbar -->\r\n");
      out.write("    <div class=\"container-fluid py-4\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-xl-0 mb-4\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\">ZIGZAG</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      16,548,120원\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+24%</span>\r\n");
      out.write("                      \r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                   <img src=\"/image/img/zig.png\" style=\"width: 50px;\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-xl-0 mb-4\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\">EMART</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      15,847,120원\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+18%</span>\r\n");
      out.write("                      \r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <img src=\"/image/img/emart.png\" style=\"width: 50px;\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-xl-0 mb-4\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\">AGODA</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      13,987,530원\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+12%</span>\r\n");
      out.write("                      \r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <img src=\"/image/img/agoda.png\" style=\"width: 50px;\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\">STARBUCKS</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      915,580원\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+5%</span> \r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <img src=\"/image/img/star.png\" style=\"width: 50px;\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-lg-7 mb-lg-0 mb-4\">\r\n");
      out.write("          <div class=\"card z-index-2 h-100\">\r\n");
      out.write("            <div class=\"card-header pb-0 pt-3 bg-transparent\">\r\n");
      out.write("              <h6 class=\"text-capitalize\">적금 상품 가입자 수</h6>\r\n");
      out.write("              <p class=\"text-sm mb-0\">\r\n");
      out.write("                <span class=\"font-weight-bold\">");
      out.print(year);
      out.write('-');
      out.print(month);
      out.write(" 기준</span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"chart\">\r\n");
      out.write("                <canvas id=\"chart-line\" class=\"chart-canvas\" height=\"300\"></canvas>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-5\">\r\n");
      out.write("          <div class=\"card card-carousel overflow-hidden h-100 p-0\">\r\n");
      out.write("            <div id=\"carouselExampleCaptions\" class=\"carousel slide h-100\" data-bs-ride=\"carousel\">\r\n");
      out.write("              <div class=\"carousel-inner border-radius-lg h-100\">\r\n");
      out.write("                <div class=\"carousel-item h-100 active\" >\r\n");
      out.write("		          <div class=\"card\">\r\n");
      out.write("		            <div class=\"card-header pb-0 p-3\">\r\n");
      out.write("		              <h6 class=\"mb-0\">쿠폰 현황</h6>\r\n");
      out.write("		            </div>\r\n");
      out.write("		            <div class=\"card-body\" style=\"height: 360px;\">\r\n");
      out.write("		              <ul class=\"list-group\">\r\n");
      out.write("		                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("		                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("		                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("		                      <i class=\"ni fa-regular fa-1 text-white opacity-10\"></i>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"d-flex flex-column\">\r\n");
      out.write("		                      <h6 class=\"mb-1 text-dark text-sm\">GS25</h6>\r\n");
      out.write("		                      <span class=\"text-xs\">35장 <span class=\"font-weight-bold\"></span></span>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                  <div class=\"d-flex\">\r\n");
      out.write("		                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </li>\r\n");
      out.write("		                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("		                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("		                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("		                      <i class=\"ni fa-regular fa-2 text-white opacity-10\"></i>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"d-flex flex-column\">\r\n");
      out.write("		                      <h6 class=\"mb-1 text-dark text-sm\">ABLY</h6>\r\n");
      out.write("		                      <span class=\"text-xs\">27장 </span>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                  <div class=\"d-flex\">\r\n");
      out.write("		                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </li>\r\n");
      out.write("		                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("		                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("		                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("		                      <i class=\"ni fa-regular fa-3 text-white opacity-10\"></i>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"d-flex flex-column\">\r\n");
      out.write("		                      <h6 class=\"mb-1 text-dark text-sm\">YOGIYO</h6>\r\n");
      out.write("		                      <span class=\"text-xs\">21장</span>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                  <div class=\"d-flex\">\r\n");
      out.write("		                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </li>\r\n");
      out.write("		                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("		                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("		                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("		                      <i class=\"ni fa-regular fa-4 text-white opacity-10\"></i>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"d-flex flex-column\">\r\n");
      out.write("		                      <h6 class=\"mb-1 text-dark text-sm\">MUSINSA</h6>\r\n");
      out.write("		                      <span class=\"text-xs font-weight-bold\">14장</span>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                  <div class=\"d-flex\">\r\n");
      out.write("		                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </li>\r\n");
      out.write("		                   <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("		                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("		                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("		                      <i class=\"ni fa-regular fa-5 text-white opacity-10\"></i>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <div class=\"d-flex flex-column\">\r\n");
      out.write("		                      <h6 class=\"mb-1 text-dark text-sm\">EDIYA</h6>\r\n");
      out.write("		                      <span class=\"text-xs\">8장 <span class=\"font-weight-bold\"></span></span>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                  <div class=\"d-flex\">\r\n");
      out.write("		                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </li>\r\n");
      out.write("		              </ul>\r\n");
      out.write("		            </div>\r\n");
      out.write("		          </div>\r\n");
      out.write("     \r\n");
      out.write("                <!--   <div class=\"carousel-caption d-none d-md-block bottom-0 text-start start-0 ms-5\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm bg-white text-center border-radius-md mb-3\">\r\n");
      out.write("                      <i class=\"ni ni-camera-compact text-dark opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-white mb-1\">Get started with Argon</h5>\r\n");
      out.write("                    <p>There’s nothing I really wanted to do in life that I wasn’t able to get good at.</p>\r\n");
      out.write("                  </div> -->\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button class=\"carousel-control-prev w-5 me-3\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <button class=\"carousel-control-next w-5 me-3\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-lg-12 mb-lg-0 mb-4\">\r\n");
      out.write("          <div class=\"card \">\r\n");
      out.write("            <div class=\"card-header pb-0 p-3\">\r\n");
      out.write("              <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <h6 class=\"mb-2\">적금 상품 목록</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("              <table class=\"table align-items-center \">\r\n");
      out.write("              	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <footer class=\"footer pt-3  \">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row align-items-center justify-content-lg-between\">\r\n");
      out.write("            <div class=\"col-lg-6 mb-lg-0 mb-4\">\r\n");
      out.write("              <div class=\"copyright text-center text-sm text-muted text-lg-start\">\r\n");
      out.write("                © <script>\r\n");
      out.write("                  document.write(new Date().getFullYear())\r\n");
      out.write("                </script>,\r\n");
      out.write("                made with <i class=\"fa fa-heart\"></i> by\r\n");
      out.write("                <a href=\"https://www.creative-tim.com\" class=\"font-weight-bold\" target=\"_blank\">Creative Tim</a>\r\n");
      out.write("                for a better web.\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <ul class=\"nav nav-footer justify-content-center justify-content-lg-end\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com\" class=\"nav-link text-muted\" target=\"_blank\">Creative Tim</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com/presentation\" class=\"nav-link text-muted\" target=\"_blank\">About Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com/blog\" class=\"nav-link text-muted\" target=\"_blank\">Blog</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com/license\" class=\"nav-link pe-0 text-muted\" target=\"_blank\">License</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("  <div id=\"admin_chat\" class=\"fixed-plugin\">\r\n");
      out.write(" 	<a href=\"javascript:open_chat();\" class=\"fixed-plugin-button text-dark position-fixed px-3 py-2\" style=\"width: 70px; height: 70px;\" id=\"chat\">\r\n");
      out.write("      <img src=\"/image/img/talk.png\" style=\"width: 40px; padding-top: 5px;\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"card shadow-lg\" style=\"height: 80%; top: 180px; border: 3px solid rgb(9,154,150); border-radius: 50px;\">\r\n");
      out.write("      <div class=\"card-header pb-0 pt-3 \" style=\"border-radius: 50px;margin-bottom: 15px;\">\r\n");
      out.write("        <div class=\"float-start\">\r\n");
      out.write("          <h5 class=\"mt-3 mb-0\">실시간 채팅 상담</h5>\r\n");
      out.write("          <p>채팅을 통해 문의를 남겨주세요 </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"float-end mt-4\">\r\n");
      out.write("          <button class=\"btn btn-link text-dark p-0 fixed-plugin-close-button\">\r\n");
      out.write("            <i class=\"fa fa-close\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Toggle Button -->\r\n");
      out.write("      </div>	\r\n");
      out.write("      <div class=\"card-body pt-sm-3 pt-0 overflow-auto\" style=\"border-radius: 20px; box-shadow: 2px 2px 2px 2px rgba(151,151,151,0.2); flex: none; width: 400px; margin-left: 15px; height: 520px;\">\r\n");
      out.write("        <!-- Navbar Fixed -->\r\n");
      out.write("        <div class=\"mt-2 mb-5 d-flex\">\r\n");
      out.write("          <h6 id=\"greetings\" class=\"mb-0\"></h6>\r\n");
      out.write("          <div class=\"form-check form-switch ps-0 ms-auto my-auto\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-body pt-sm-3 pt-0 overflow-auto\" style=\"padding-left: 20px; padding-right: 10px; margin-top: 5px;\">\r\n");
      out.write("     	<input id=\"name\" type=\"text\" style=\"outline: none; width: 310px; border-radius: 10px; height: 40px; border: none; box-shadow: 2px 2px 2px 2px rgba(151,151,151,0.3)\">\r\n");
      out.write("     	<button onclick=\"sendName();\" class=\"btn bg-gradient-primary px-3 active\" data-class=\"bg-white\" style=\"margin-bottom: 0px; margin-left: 15px;\">전송</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   Core JS Files   -->\r\n");
      out.write("  <script src=\"/js/core/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/plugins/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/plugins/smooth-scrollbar.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/plugins/chartjs.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    var ctx1 = document.getElementById(\"chart-line\").getContext(\"2d\");\r\n");
      out.write("\r\n");
      out.write("    var gradientStroke1 = ctx1.createLinearGradient(0, 230, 0, 50);\r\n");
      out.write("\r\n");
      out.write("    gradientStroke1.addColorStop(1, 'rgba(9, 154, 150, 0.2)');\r\n");
      out.write("    gradientStroke1.addColorStop(0.2, 'rgba(50, 173, 170, 0.0)');\r\n");
      out.write("    gradientStroke1.addColorStop(0, 'rgba(86, 191, 188, 0)');\r\n");
      out.write("    new Chart(ctx1, {\r\n");
      out.write("      type: \"line\",\r\n");
      out.write("      data: {\r\n");
      out.write("        labels: [\"1월\", \"2월\", \"3월\", \"4월\", \"5월\", \"6월\", \"7월\", \"8월\", \"9월\"],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("          label: \"SAVING\",\r\n");
      out.write("          tension: 0.4,\r\n");
      out.write("          borderWidth: 0,\r\n");
      out.write("          pointRadius: 0,\r\n");
      out.write("          borderColor: \"#099A96\",\r\n");
      out.write("          backgroundColor: gradientStroke1,\r\n");
      out.write("          borderWidth: 3,\r\n");
      out.write("          fill: true,\r\n");
      out.write("          data: [0, 5, 18, 10, 15, 28,38, 22, 35],\r\n");
      out.write("          maxBarThickness: 6\r\n");
      out.write("\r\n");
      out.write("        }],\r\n");
      out.write("      },\r\n");
      out.write("      options: {\r\n");
      out.write("        responsive: true,\r\n");
      out.write("        maintainAspectRatio: false,\r\n");
      out.write("        plugins: {\r\n");
      out.write("          legend: {\r\n");
      out.write("            display: false,\r\n");
      out.write("          }\r\n");
      out.write("        },\r\n");
      out.write("        interaction: {\r\n");
      out.write("          intersect: false,\r\n");
      out.write("          mode: 'index',\r\n");
      out.write("        },\r\n");
      out.write("        scales: {\r\n");
      out.write("          y: {\r\n");
      out.write("            grid: {\r\n");
      out.write("              drawBorder: false,\r\n");
      out.write("              display: true,\r\n");
      out.write("              drawOnChartArea: true,\r\n");
      out.write("              drawTicks: false,\r\n");
      out.write("              borderDash: [5, 5]\r\n");
      out.write("            },\r\n");
      out.write("            ticks: {\r\n");
      out.write("              display: true,\r\n");
      out.write("              padding: 10,\r\n");
      out.write("              color: '#fbfbfb',\r\n");
      out.write("              font: {\r\n");
      out.write("                size: 11,\r\n");
      out.write("                family: \"Open Sans\",\r\n");
      out.write("                style: 'normal',\r\n");
      out.write("                lineHeight: 2\r\n");
      out.write("              },\r\n");
      out.write("            }\r\n");
      out.write("          },\r\n");
      out.write("          x: {\r\n");
      out.write("            grid: {\r\n");
      out.write("              drawBorder: false,\r\n");
      out.write("              display: false,\r\n");
      out.write("              drawOnChartArea: false,\r\n");
      out.write("              drawTicks: false,\r\n");
      out.write("              borderDash: [5, 5]\r\n");
      out.write("            },\r\n");
      out.write("            ticks: {\r\n");
      out.write("              display: true,\r\n");
      out.write("              color: '#555',\r\n");
      out.write("              padding: 20,\r\n");
      out.write("              font: {\r\n");
      out.write("                size: 11,\r\n");
      out.write("                family: \"Open Sans\",\r\n");
      out.write("                style: 'normal',\r\n");
      out.write("                lineHeight: 2\r\n");
      out.write("              },\r\n");
      out.write("            }\r\n");
      out.write("          },\r\n");
      out.write("        },\r\n");
      out.write("      },\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("  <script>\r\n");
      out.write("    var win = navigator.platform.indexOf('Win') > -1;\r\n");
      out.write("    if (win && document.querySelector('#sidenav-scrollbar')) {\r\n");
      out.write("      var options = {\r\n");
      out.write("        damping: '0.5'\r\n");
      out.write("      }\r\n");
      out.write("      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("  <script src=\"/webjars/sockjs-client/sockjs.min.js\"></script>\r\n");
      out.write("  <script src=\"/webjars/stomp-websocket/stomp.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/websocket/websocket.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  	function open_chat() {\r\n");
      out.write("  		connect();\r\n");
      out.write("  		$('#admin_chat').addClass('show');\r\n");
      out.write("  	}\r\n");
      out.write("  </script>\r\n");
      out.write("  <!-- Github buttons -->\r\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("  <script src=\"/js/argon-dashboard.min.js?v=2.0.4\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/admin/detail.jsp(468,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/admin/detail.jsp(468,15) '${productList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/admin/detail.jsp(468,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("productList");
      // /WEB-INF/jsp/admin/detail.jsp(468,15) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                <tbody>\r\n");
            out.write("                  <tr style=\"border-bottom: 1px solid lightgray;\">\r\n");
            out.write("                    <td class=\"w-30\">\r\n");
            out.write("                      <div class=\"d-flex px-2 py-1 align-items-center\">\r\n");
            out.write("                        <div class=\"ms-4\">\r\n");
            out.write("                          <p class=\"text-xs font-weight-bold mb-2\">상품</p>\r\n");
            out.write("                          <h6 class=\"text-sm mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList['SAVINGNAME'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                        </div>\r\n");
            out.write("                      </div>\r\n");
            out.write("                    </td>\r\n");
            out.write("                    <td>\r\n");
            out.write("                      <div class=\"text-center\">\r\n");
            out.write("                        <p class=\"text-xs font-weight-bold mb-2\">기본금리</p>\r\n");
            out.write("                        <h6 class=\"text-sm mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList['BASERATE'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" %</h6>\r\n");
            out.write("                      </div>\r\n");
            out.write("                    </td>\r\n");
            out.write("                    <td>\r\n");
            out.write("                      <div class=\"text-center\">\r\n");
            out.write("                        <p class=\"text-xs font-weight-bold mb-2\">우대금리</p>\r\n");
            out.write("                        <h6 class=\"text-sm mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList['PRIMERATE'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" %</h6>\r\n");
            out.write("                      </div>\r\n");
            out.write("                    </td>\r\n");
            out.write("                    <td class=\"align-middle text-sm\">\r\n");
            out.write("                      <div class=\"col text-center\">\r\n");
            out.write("                        <p class=\"text-xs font-weight-bold mb-2\">카테고리</p>\r\n");
            out.write("                        <h6 class=\"text-sm mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList['CATEGORY']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                      </div>\r\n");
            out.write("                    </td>\r\n");
            out.write("                    <td>\r\n");
            out.write("                      <div class=\"text-center\">\r\n");
            out.write("                        <p class=\"text-xs font-weight-bold mb-2\">등록일</p>\r\n");
            out.write("                        <h6 class=\"text-sm mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList['ADDDATE'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </h6>\r\n");
            out.write("                      </div>\r\n");
            out.write("                    </td>\r\n");
            out.write("                  </tr>\r\n");
            out.write("                 \r\n");
            out.write("                </tbody>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
