/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-12 05:04:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.ac.kopo.Util;
import java.util.Calendar;

public final class productAdminInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.22.jar", Long.valueOf(1665220669260L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/spring-webmvc-5.3.22.jar!/META-INF/spring-form.tld", Long.valueOf(1657755656000L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1665220674434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.ac.kopo.Util");
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\"/>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/image/img/apple-icon.png\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"/image/img/favicon.png\">\r\n");
      out.write("  <title>\r\n");
      out.write("    product\r\n");
      out.write("  </title>\r\n");
      out.write("  <!--     Fonts and icons     -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Nucleo Icons -->\r\n");
      out.write("  <link href=\"/style/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"/style/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/42d5adcbca.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link href=\"/style/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- CSS Files -->\r\n");
      out.write("  \r\n");
      out.write("  <link id=\"pagestyle\" href=\"/style/css/argon-dashboard.css?v=2.0.4\" rel=\"stylesheet\" />\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/b3a7369db8.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/style/css/main.css\" />\r\n");
      out.write("  <script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("	#form{\r\n");
      out.write("		height: 50px; margin-bottom: 30px;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"g-sidenav-show   bg-gray-100\">\r\n");
 
String year = request.getParameter("year");
String month = request.getParameter("month");

year = Util.getStringNowYear();
month = Util.getStringNowMonth();

      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /WEB-INF/jsp/admin/productAdminInsert.jsp(56,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("year");
        // /WEB-INF/jsp/admin/productAdminInsert.jsp(56,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(year);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /WEB-INF/jsp/admin/productAdminInsert.jsp(57,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("month");
        // /WEB-INF/jsp/admin/productAdminInsert.jsp(57,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(month);
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("  \r\n");
      out.write("  <div class=\"min-height-300 bg-primary position-absolute w-100\" style=\"background-color: rgb(9,154,150) !important\"></div>\r\n");
      out.write("  <aside class=\"sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 \" id=\"sidenav-main\">\r\n");
      out.write("    <div class=\"sidenav-header\">\r\n");
      out.write("      <i class=\"fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none\" aria-hidden=\"true\" id=\"iconSidenav\"></i>\r\n");
      out.write("      <a class=\"navbar-brand m-0\" href=\" https://demos.creative-tim.com/argon-dashboard/pages/dashboard.html \" target=\"_blank\">\r\n");
      out.write("        <img src=\"/image/logo/logo2.png\" class=\"navbar-brand-img h-100\" alt=\"main_logo\">\r\n");
      out.write("        <span class=\"ms-1 font-weight-bold\" style=\"position: relative;bottom: 12px; right: 2px;\">하나챌린지</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr class=\"horizontal dark mt-0\">\r\n");
      out.write("    <div class=\"collapse navbar-collapse  w-auto \" id=\"sidenav-collapse-main\">\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" href=\"./pages/dashboard.html\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-tv-2 text-primary text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">대시보드</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"./pages/tables.html\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-app text-warning text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">상품</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/email\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("               <i class=\"ni fa-regular fa-envelope text-success text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">메일</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"./pages/billing.html\">\r\n");
      out.write("      \r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-collection text-info text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">쿠폰</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sidenav-footer mx-3 \">\r\n");
      out.write("      <div class=\"card card-plain shadow-none\" id=\"sidenavCard\">\r\n");
      out.write("       <img class=\"w-50 mx-auto\" src=\"/image/img/illustrations/icon-documentation.svg\" alt=\"sidebar_illustration\">\r\n");
      out.write("        <div class=\"card-body text-center p-3 w-100 pt-0\">\r\n");
      out.write("          <div class=\"docs-info\">\r\n");
      out.write("            <h6 class=\"mb-0\">Need help?</h6>\r\n");
      out.write("            <p class=\"text-xs font-weight-bold mb-0\">Please check our docs</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a href=\"https://www.creative-tim.com/learning-lab/bootstrap/license/argon-dashboard\" target=\"_blank\" class=\"btn btn-dark btn-sm w-100 mb-3\">Documentation</a>\r\n");
      out.write("      <a class=\"btn btn-primary btn-sm mb-0 w-100\" href=\"https://www.creative-tim.com/product/argon-dashboard-pro?ref=sidebarfree\" type=\"button\">Upgrade to pro</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <main class=\"main-content position-relative border-radius-lg \">\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl \" id=\"navbarBlur\" data-scroll=\"false\">\r\n");
      out.write("      <div class=\"container-fluid py-1 px-3\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("          <ol class=\"breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5\">\r\n");
      out.write("            <li class=\"breadcrumb-item text-sm\"><a class=\"opacity-5 text-white\" href=\"javascript:;\">Pages</a></li>\r\n");
      out.write("            <li class=\"breadcrumb-item text-sm text-white active\" aria-current=\"page\">Product</li>\r\n");
      out.write("          </ol>\r\n");
      out.write("          <h4 class=\"font-weight-bolder text-white mb-0\" style=\"font-size: 25px;\">상품</h4>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4\" id=\"navbar\">\r\n");
      out.write("          <div class=\"ms-md-auto pe-md-3 d-flex align-items-center\">\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("              <span class=\"input-group-text text-body\"><i class=\"fas fa-search\" aria-hidden=\"true\"></i></span>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Type here...\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"navbar-nav  justify-content-end\">\r\n");
      out.write("            <li class=\"nav-item d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white font-weight-bold px-0\">\r\n");
      out.write("                <i class=\"fa fa-user me-sm-1\"></i>\r\n");
      out.write("               \r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item d-xl-none ps-3 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\" id=\"iconNavbarSidenav\">\r\n");
      out.write("                <div class=\"sidenav-toggler-inner\">\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item px-3 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\">\r\n");
      out.write("                <i class=\"fa fa-cog fixed-plugin-button-nav cursor-pointer\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown pe-2 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\" id=\"dropdownMenuButton\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fa fa-bell cursor-pointer\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                <li class=\"mb-2\">\r\n");
      out.write("                  <a class=\"dropdown-item border-radius-md\" href=\"javascript:;\">\r\n");
      out.write("                    <div class=\"d-flex py-1\">\r\n");
      out.write("                      <div class=\"my-auto\">\r\n");
      out.write("                        <img src=\"../assets/img/team-2.jpg\" class=\"avatar avatar-sm  me-3 \">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex flex-column justify-content-center\">\r\n");
      out.write("                        <h6 class=\"text-sm font-weight-normal mb-1\">\r\n");
      out.write("                          <span class=\"font-weight-bold\">New message</span> from Laur\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        <p class=\"text-xs text-secondary mb-0\">\r\n");
      out.write("                          <i class=\"fa fa-clock me-1\"></i>\r\n");
      out.write("                          13 minutes ago\r\n");
      out.write("                        </p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"mb-2\">\r\n");
      out.write("                  <a class=\"dropdown-item border-radius-md\" href=\"javascript:;\">\r\n");
      out.write("                    <div class=\"d-flex py-1\">\r\n");
      out.write("                      <div class=\"my-auto\">\r\n");
      out.write("                        <img src=\"../assets/img/small-logos/logo-spotify.svg\" class=\"avatar avatar-sm bg-gradient-dark  me-3 \">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex flex-column justify-content-center\">\r\n");
      out.write("                        <h6 class=\"text-sm font-weight-normal mb-1\">\r\n");
      out.write("                          <span class=\"font-weight-bold\">New album</span> by Travis Scott\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        <p class=\"text-xs text-secondary mb-0\">\r\n");
      out.write("                          <i class=\"fa fa-clock me-1\"></i>\r\n");
      out.write("                          1 day\r\n");
      out.write("                        </p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"dropdown-item border-radius-md\" href=\"javascript:;\">\r\n");
      out.write("                    <div class=\"d-flex py-1\">\r\n");
      out.write("                      <div class=\"avatar avatar-sm bg-gradient-secondary  me-3  my-auto\">\r\n");
      out.write("                        <svg width=\"12px\" height=\"12px\" viewBox=\"0 0 43 36\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n");
      out.write("                          <title>credit-card</title>\r\n");
      out.write("                          <g stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("                            <g transform=\"translate(-2169.000000, -745.000000)\" fill=\"#FFFFFF\" fill-rule=\"nonzero\">\r\n");
      out.write("                              <g transform=\"translate(1716.000000, 291.000000)\">\r\n");
      out.write("                                <g transform=\"translate(453.000000, 454.000000)\">\r\n");
      out.write("                                  <path class=\"color-background\" d=\"M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z\" opacity=\"0.593633743\"></path>\r\n");
      out.write("                                  <path class=\"color-background\" d=\"M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z\"></path>\r\n");
      out.write("                                </g>\r\n");
      out.write("                              </g>\r\n");
      out.write("                            </g>\r\n");
      out.write("                          </g>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"d-flex flex-column justify-content-center\">\r\n");
      out.write("                        <h6 class=\"text-sm font-weight-normal mb-1\">\r\n");
      out.write("                          Payment successfully completed\r\n");
      out.write("                        </h6>\r\n");
      out.write("                        <p class=\"text-xs text-secondary mb-0\">\r\n");
      out.write("                          <i class=\"fa fa-clock me-1\"></i>\r\n");
      out.write("                          2 days\r\n");
      out.write("                        </p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- End Navbar -->\r\n");
      out.write("    <div class=\"container-fluid py-4\" style=\"margin-top: 30px;\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header pb-0\" style=\"padding: 30px 50px 20px 50px;\">\r\n");
      out.write("              <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <p class=\"mb-0 font-weight-bolder\" style=\"font-size: 28px; color: #344767 !important;\">상품 등록</p>               \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form name=\"form1\" action=\"/productAdminInsertProc\" method=\"post\">\r\n");
      out.write("            <div class=\"card-body\" style=\"padding: 40px 50px 100px 50px;\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">상품 이름</label>\r\n");
      out.write("                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"savingName\" value=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">상품 카테고리</label>\r\n");
      out.write("                    <select class=\"form-control\" id=\"form\" name=\"consumeCode\" style=\"width: 100%;\">\r\n");
      out.write("                       	<option value=\"\">선택하세요</option>\r\n");
      out.write("                       	<option value=\"01\">쇼핑/뷰티</option>\r\n");
      out.write("                       	<option value=\"02\">식비</option>\r\n");
      out.write("                       	<option value=\"03\">주거/통신</option>\r\n");
      out.write("                       	<option value=\"04\">여행/숙박</option>\r\n");
      out.write("                       	<option value=\"05\">의료/건강</option>\r\n");
      out.write("                       	<option value=\"06\">카페/디저트</option>\r\n");
      out.write("                       	<option value=\"07\">편의점/마트</option>\r\n");
      out.write("                       	<option value=\"08\">문화생활</option>\r\n");
      out.write("                       	<option value=\"09\">교통/자동차</option>\r\n");
      out.write("                       	<option value=\"10\">기타</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <!-- <input class=\"form-control\" type=\"text\" name=\"consumeCode\" value=\"\"> -->\r\n");
      out.write("                    \r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">상품 상세</label>\r\n");
      out.write("                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"savingDetail\" value=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">기본 금리</label>\r\n");
      out.write("                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"baseRate\" value=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">우대 금리</label>\r\n");
      out.write("                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"primeRate\" value=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">최소 가입 금액</label>\r\n");
      out.write("                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"minAmount\" value=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">최대 가입 금액</label>\r\n");
      out.write("                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"maxAmount\" value=\"\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("	              <div class=\"row\">\r\n");
      out.write("	                <div class=\"col-md-3\">\r\n");
      out.write("	                  <div class=\"form-group\">\r\n");
      out.write("	                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">최소 가입 나이</label>\r\n");
      out.write("	                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"minAge\" value=\"\">\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-md-3\">\r\n");
      out.write("	                  <div class=\"form-group\">\r\n");
      out.write("	                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">최대 가입 나이</label>\r\n");
      out.write("	                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"maxAge\" value=\"\">\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-md-3\">\r\n");
      out.write("	                  <div class=\"form-group\">\r\n");
      out.write("	                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">최소 가입 기간</label>\r\n");
      out.write("	                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"minPeriod\" value=\"\">\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"col-md-3\">\r\n");
      out.write("	                  <div class=\"form-group\">\r\n");
      out.write("	                    <label for=\"example-text-input\" class=\"form-control-label\" style=\"font-size: 18px; margin-bottom: 15px;\">최대 가입 기간</label>\r\n");
      out.write("	                    <input id=\"form\" class=\"form-control\" type=\"text\" name=\"maxPeriod\" value=\"\">\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	              </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div style=\"position: relative; top: 35px;\" align=\"center\">\r\n");
      out.write("              <input class=\"openBtn\" type=\"submit\" value=\"등록\" style=\"font-size: 18px; height: 45px;\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("         <!-- Modal -->\r\n");
      out.write("			       		\r\n");
      out.write("      \r\n");
      out.write("      <footer class=\"footer pt-3  \">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row align-items-center justify-content-lg-between\">\r\n");
      out.write("            <div class=\"col-lg-6 mb-lg-0 mb-4\">\r\n");
      out.write("              <div class=\"copyright text-center text-sm text-muted text-lg-start\">\r\n");
      out.write("                <script>\r\n");
      out.write("                  document.write(new Date().getFullYear())\r\n");
      out.write("                </script>,\r\n");
      out.write("                made with <i class=\"fa fa-heart\"></i> by\r\n");
      out.write("                <a href=\"https://www.creative-tim.com\" class=\"font-weight-bold\" target=\"_blank\">Creative Tim</a>\r\n");
      out.write("                for a better web.\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("              <ul class=\"nav nav-footer justify-content-center justify-content-lg-end\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com\" class=\"nav-link text-muted\" target=\"_blank\">Creative Tim</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com/presentation\" class=\"nav-link text-muted\" target=\"_blank\">About Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com/blog\" class=\"nav-link text-muted\" target=\"_blank\">Blog</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"https://www.creative-tim.com/license\" class=\"nav-link pe-0 text-muted\" target=\"_blank\">License</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("  <div class=\"fixed-plugin\">\r\n");
      out.write("    <a class=\"fixed-plugin-button text-dark position-fixed px-3 py-2\">\r\n");
      out.write("      <i class=\"fa fa-cog py-2\"> </i>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"card shadow-lg\">\r\n");
      out.write("      <div class=\"card-header pb-0 pt-3 \">\r\n");
      out.write("        <div class=\"float-start\">\r\n");
      out.write("          <h5 class=\"mt-3 mb-0\">Argon Configurator</h5>\r\n");
      out.write("          <p>See our dashboard options.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"float-end mt-4\">\r\n");
      out.write("          <button class=\"btn btn-link text-dark p-0 fixed-plugin-close-button\">\r\n");
      out.write("            <i class=\"fa fa-close\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Toggle Button -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <hr class=\"horizontal dark my-1\">\r\n");
      out.write("      <div class=\"card-body pt-sm-3 pt-0 overflow-auto\">\r\n");
      out.write("        <!-- Sidebar Backgrounds -->\r\n");
      out.write("        <div>\r\n");
      out.write("          <h6 class=\"mb-0\">Sidebar Colors</h6>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"switch-trigger background-color\">\r\n");
      out.write("          <div class=\"badge-colors my-2 text-start\">\r\n");
      out.write("            <span class=\"badge filter bg-gradient-primary active\" data-color=\"primary\" onclick=\"sidebarColor(this)\"></span>\r\n");
      out.write("            <span class=\"badge filter bg-gradient-dark\" data-color=\"dark\" onclick=\"sidebarColor(this)\"></span>\r\n");
      out.write("            <span class=\"badge filter bg-gradient-info\" data-color=\"info\" onclick=\"sidebarColor(this)\"></span>\r\n");
      out.write("            <span class=\"badge filter bg-gradient-success\" data-color=\"success\" onclick=\"sidebarColor(this)\"></span>\r\n");
      out.write("            <span class=\"badge filter bg-gradient-warning\" data-color=\"warning\" onclick=\"sidebarColor(this)\"></span>\r\n");
      out.write("            <span class=\"badge filter bg-gradient-danger\" data-color=\"danger\" onclick=\"sidebarColor(this)\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <!-- Sidenav Type -->\r\n");
      out.write("        <div class=\"mt-3\">\r\n");
      out.write("          <h6 class=\"mb-0\">Sidenav Type</h6>\r\n");
      out.write("          <p class=\"text-sm\">Choose between 2 different sidenav types.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"d-flex\">\r\n");
      out.write("          <button class=\"btn bg-gradient-primary w-100 px-3 mb-2 active me-2\" data-class=\"bg-white\" onclick=\"sidebarType(this)\">White</button>\r\n");
      out.write("          <button class=\"btn bg-gradient-primary w-100 px-3 mb-2\" data-class=\"bg-default\" onclick=\"sidebarType(this)\">Dark</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"text-sm d-xl-none d-block mt-2\">You can change the sidenav type just on desktop view.</p>\r\n");
      out.write("        <!-- Navbar Fixed -->\r\n");
      out.write("        <div class=\"d-flex my-3\">\r\n");
      out.write("          <h6 class=\"mb-0\">Navbar Fixed</h6>\r\n");
      out.write("          <div class=\"form-check form-switch ps-0 ms-auto my-auto\">\r\n");
      out.write("            <input class=\"form-check-input mt-1 ms-auto\" type=\"checkbox\" id=\"navbarFixed\" onclick=\"navbarFixed(this)\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"horizontal dark my-sm-4\">\r\n");
      out.write("        <div class=\"mt-2 mb-5 d-flex\">\r\n");
      out.write("          <h6 class=\"mb-0\">Light / Dark</h6>\r\n");
      out.write("          <div class=\"form-check form-switch ps-0 ms-auto my-auto\">\r\n");
      out.write("            <input class=\"form-check-input mt-1 ms-auto\" type=\"checkbox\" id=\"dark-version\" onclick=\"darkMode(this)\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"btn bg-gradient-dark w-100\" href=\"https://www.creative-tim.com/product/argon-dashboard\">Free Download</a>\r\n");
      out.write("        <a class=\"btn btn-outline-dark w-100\" href=\"https://www.creative-tim.com/learning-lab/bootstrap/license/argon-dashboard\">View documentation</a>\r\n");
      out.write("        <div class=\"w-100 text-center\">\r\n");
      out.write("          <a class=\"github-button\" href=\"https://github.com/creativetimofficial/argon-dashboard\" data-icon=\"octicon-star\" data-size=\"large\" data-show-count=\"true\" aria-label=\"Star creativetimofficial/argon-dashboard on GitHub\">Star</a>\r\n");
      out.write("          <h6 class=\"mt-3\">Thank you for sharing!</h6>\r\n");
      out.write("          <a href=\"https://twitter.com/intent/tweet?text=Check%20Argon%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fargon-dashboard\" class=\"btn btn-dark mb-0 me-2\" target=\"_blank\">\r\n");
      out.write("            <i class=\"fab fa-twitter me-1\" aria-hidden=\"true\"></i> Tweet\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://www.facebook.com/sharer/sharer.php?u=https://www.creative-tim.com/product/argon-dashboard\" class=\"btn btn-dark mb-0 me-2\" target=\"_blank\">\r\n");
      out.write("            <i class=\"fab fa-facebook-square me-1\" aria-hidden=\"true\"></i> Share\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   Core JS Files   -->\r\n");
      out.write("  <script src=\"/js/core/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/plugins/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/plugins/smooth-scrollbar.min.js\"></script>\r\n");
      out.write("  <script src=\"/js/plugins/chartjs.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write(" <!-- Github buttons -->\r\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("  <script src=\"/js/argon-dashboard.min.js?v=2.0.4\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
