/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-09 07:44:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.ac.kopo.Util;
import java.util.Calendar;

public final class shoppingProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.22.jar", Long.valueOf(1665220669260L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/spring-webmvc-5.3.22.jar!/META-INF/spring-form.tld", Long.valueOf(1657755656000L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1665220674434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.ac.kopo.Util");
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/main2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/table.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("        .chal:after{\r\n");
      out.write("	       	content: \"\";\r\n");
      out.write("	        display: block;\r\n");
      out.write("	        width: 60px;\r\n");
      out.write("	        border-bottom: 1.5px solid rgb(9,154,150);\r\n");
      out.write("	        margin: 0px auto;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("   		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<main class=\"hana__main-wrap\" style=\"margin: 155px 140px\">\r\n");
      out.write("		<h1 align=\"center\" style=\"font-size: 32px; font-weight: bold;\" class=\"container-fluid fw-bold font-sans-serif py-4\">쇼핑/뷰티 맞춤상품</h1>\r\n");
      out.write("		<a class=\"chal\"\"></a>\r\n");
      out.write("			<div class=\"d-flex\" style=\"margin-top: 50px;\">\r\n");
      out.write("			<div>\r\n");
      out.write("			<img src = \"/image/img/musinsa.png\" style=\"width: 530px; margin-left: 150px;\">\r\n");
      out.write("				<div style=\"width: 40%; margin-left: 330px; margin-top: 25px;\">\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shoppingProductJoin1\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingCode\" name=\"savingCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[0]['SAVINGCODE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"interestRate\" name=\"interestRate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[0]['BASERATE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingName\" name=\"savingName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[0]['SAVINGNAME']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input class=\"homeBtn\" type=\"submit\" value=\"가입하기\" style=\"text-align: center; width: 150px; font-size: 18px;\" >\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("			<img src = \"/image/img/oliveyoung.png\" style=\"width: 530px; margin-left: 50px;\">\r\n");
      out.write("				<div style=\"width: 40%; margin-left: 250px; margin-top: 25px;\">\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shoppingProductJoin1\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingCode\" name=\"savingCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[1]['SAVINGCODE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"interestRate\" name=\"interestRate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[1]['BASERATE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingName\" name=\"savingName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[1]['SAVINGNAME']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input class=\"homeBtn\" type=\"submit\" value=\"가입하기\" style=\"text-align: center; width: 150px; font-size: 18px;\" >\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"d-flex\" style=\"margin-top: 50px;\">\r\n");
      out.write("			<div>\r\n");
      out.write("			<img src = \"/image/img/trenbe.png\" style=\"width: 530px; margin-left: 150px;\">\r\n");
      out.write("				<div style=\"width: 40%; margin-left: 330px; margin-top: 25px;\">\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shoppingProductJoin1\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingCode\" name=\"savingCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[3]['SAVINGCODE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"interestRate\" name=\"interestRate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[3]['BASERATE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingName\" name=\"savingName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[3]['SAVINGNAME']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input class=\"homeBtn\" type=\"submit\" value=\"가입하기\" style=\"text-align: center; width: 150px; font-size: 18px;\" >\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("			<img src = \"/image/img/ably.png\" style=\"width: 530px; margin-left: 50px;\">\r\n");
      out.write("				<div style=\"width: 40%; margin-left: 250px; margin-top: 25px;\">\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shoppingProductJoin1\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingCode\" name=\"savingCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[2]['SAVINGCODE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"interestRate\" name=\"interestRate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[2]['BASERATE']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" id=\"savingName\" name=\"savingName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectSaving[2]['SAVINGNAME']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input class=\"homeBtn\" type=\"submit\" value=\"가입하기\" style=\"text-align: center; width: 150px; font-size: 18px;\" >\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div> 	\r\n");
      out.write("		\r\n");
      out.write("	</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
