/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-09 07:44:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.ac.kopo.Util;
import java.util.Calendar;

public final class shoppingProductJoin1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.22.jar", Long.valueOf(1665220669260L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/spring-webmvc-5.3.22.jar!/META-INF/spring-form.tld", Long.valueOf(1657755656000L));
    _jspx_dependants.put("jar:file:/D:/HanaChallenge/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HanaChallenge/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1665220674434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.ac.kopo.Util");
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/theme.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/main2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style/css/table.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b3a7369db8.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	@font-face {\r\n");
      out.write("    font-family: 'InfinitySans-RegularA1';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/InfinitySans-RegularA1.woff') format('woff');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("	label {\r\n");
      out.write("	  display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.accordion-button:not(.collapsed){\r\n");
      out.write("		color : black;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("	}\r\n");
      out.write("	.accordion-button:focus{\r\n");
      out.write("		box-shadow: none;\r\n");
      out.write("	}\r\n");
      out.write("	.chal:after{\r\n");
      out.write("	       	content: \"\";\r\n");
      out.write("	        display: block;\r\n");
      out.write("	        width: 60px;\r\n");
      out.write("	        border-bottom: 1.5px solid rgb(9,154,150);\r\n");
      out.write("	        margin: 0px auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    th, tr, td{\r\n");
      out.write("    font-family: 'InfinitySans-RegularA1'\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	int savingCode = Integer.parseInt(request.getParameter("savingCode"));
	float interestrate = Float.parseFloat(request.getParameter("interestRate"));
	String savingName = request.getParameter("savingName");

      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("   		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	</header> \r\n");
      out.write("	\r\n");
      out.write("	<main class=\"hana__main-wrap\" style=\"margin: 155px 140px\">\r\n");
      out.write("		<section class=\"pt-3 pb-7 \">\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<h2 align=\"center\" class=\"container-fluid fw-bold font-sans-serif py-4\" style= \"font-size: 30px;\">");
      out.print(savingName );
      out.write(" 가입</h2>	\r\n");
      out.write("				<a class=\"chal\"\"></a>\r\n");
      out.write("			</div> \r\n");
      out.write("		\r\n");
      out.write("			<div class=\"container\" style=\"width :60%; margin-top: 50px;\">\r\n");
      out.write("				<table border=1 align=\"center\" width=100% style=\"font-family: InfinitySans-RegularA1;\">\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td style=\"width: 20%; font-weight: bold; height: 50px; padding-top: 18px; \">상품특징</td>\r\n");
      out.write("							<td>무신사 사이트에서 하나카드로 소비하는 누적 소비액에 따라 우대금리를 제공하는 상품</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td style=\"font-weight: bold; height: 50px;  padding-top: 18px;\">가입대상</td>\r\n");
      out.write("							<td>만 14세 이상 만 100세 이하</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td rowspan=\"2\" style=\"font-weight: bold; height: 50px; padding-top: 18px;\">가입기간</td>\r\n");
      out.write("							<td style=\"border-bottom: none;\">최소 6개월</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>최소 24개월</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td style=\"font-weight: bold; height: 50px; padding-top: 18px;\">가입금액</td>\r\n");
      out.write("							<td>1천원 이상 ~ 50만원 이하</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td rowspan=\"2\" style=\"font-weight: bold; height: 50px; padding-top: 18px;\">우대금리</td>\r\n");
      out.write("							<td style=\"padding-bottom: 20px;\">최대 연 5%</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td style=\"padding-left: 0px;\">\r\n");
      out.write("								<table border=1 align=\"center\" width=80%>\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th style=\"color: #555; font-weight: bold; border-bottom: 1.5px solid\">누적소비액</th>\r\n");
      out.write("											<th style=\"color: #555; font-weight: bold; border-bottom: 1.5px solid\">우대금리</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									<tbody>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"height: 40px;\">50,000원</td>\r\n");
      out.write("											<td>1.5%</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"height: 40px;\">200,000원</td>\r\n");
      out.write("											<td>2%</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"height: 40px;\">400,000원</td>\r\n");
      out.write("											<td>2.6%</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"height: 40px;\">600,000원</td>\r\n");
      out.write("											<td>3.2%</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"height: 40px;\">800,000원</td>\r\n");
      out.write("											<td>4%</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"height: 40px;\">1,000,000원</td>\r\n");
      out.write("											<td>5%</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</tbody>\r\n");
      out.write("								</table>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				\r\n");
      out.write("				<label for=\"agree_all\" style=\"margin-bottom: 25px; margin-top: 80px;\">\r\n");
      out.write("				  <input type=\"checkbox\" name=\"agree_all\" id=\"agree_all\" style =\"width: 18px; height: 16px;\">\r\n");
      out.write("				  <span style=\"font-size: 23px; text-align: center;\">모두 동의합니다</span>\r\n");
      out.write("				</label>\r\n");
      out.write("				<div class=\"accordion accordion-flush\" id=\"faqlist1\">\r\n");
      out.write("					<div class=\"accordion-item\">\r\n");
      out.write("						 <h2 class=\"accordion-header\" id=\"headingone\">\r\n");
      out.write("							<label for=\"agree\">\r\n");
      out.write("							  <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq-content-1\">\r\n");
      out.write("							  <input type=\"checkbox\" name=\"agree\" value=\"1\" style =\"width: 16px; height: 15px;\">\r\n");
      out.write("							  <span style=\"font-size: 18px;\">&nbsp적금거래기본 약관</span>\r\n");
      out.write("							  </button>\r\n");
      out.write("							</label>\r\n");
      out.write("						</h2>\r\n");
      out.write("						 	<div id=\"faq-content-1\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqlist1\">\r\n");
      out.write("                  				<div class=\"accordion-body\">\r\n");
      out.write("	                  				<p style=\"text-align: right; margin-bottom: 30px; font-size: 12px;\">개정준법감시인 심의필 제2022-약관-104호(2022.06.23)</p>\r\n");
      out.write("									<p style=\"text-align: center; font-size: 20px; font-weight: bold; margin-bottom: 50px;\">예금거래 기본약관</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 15px;\">이 적금거래기본약관(이하 “약관”이라 한다)은 (주)하나은행(이하 “은행”이라 한다)과 거래처(또는 예금주)가 서로 믿음을 바탕으로 예금거래를 빠르고 틀림 없이 처리하는 한편, 서로의 이해관계를 합리적으로 조정하기 위하여 기본적이고 일반적인 사항을 정한 것이다. 은행은 이 약관을 영업점에 놓아두고, 거래처는 영업시간 중 언제든지 이 약관을 볼 수 있고 또한 그 교부를 청구할 수 있다.</p>\r\n");
      out.write("									\r\n");
      out.write("									<p style=\"font-weight: bold; margin-bottom: 10px;\">제1조 적용범위</p>\r\n");
      out.write("									<p style= \"margin-bottom: 20px;\">이 약관은 거치식적금 및 적립식예금 거래에 적용한다.</p>\r\n");
      out.write("									\r\n");
      out.write("									<p style=\"font-weight: bold; margin-bottom: 10px;\">제2조 실명거래</p>\r\n");
      out.write("									<p style=\"margin-bottom: 8px;\">① 거래처는 실명으로 거래하여야 한다.</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 15px;\">② 은행은 거래처의 실명확인을 위하여 주민등록증ㆍ사업자등록증 등 실명확인증표 또는 그밖에 필요한 서류의 제시나 제출을 요구할 수 있고, 거래처는 이에 따라야 한다.</p>\r\n");
      out.write("									<p style=\"font-weight: bold; margin-bottom: 10px;\">제3조 거래장소</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 20px;\">거래처는 예금계좌를 개설한 영업점(이하 “개설점”이라 한다)에서 모든 예금거래를 한다. 다만, 은행이 정하는 바에 따라 다른 영업점이나 다른 금융기관, 또는 현금자동지급기ㆍ현금자동입출금기ㆍ컴퓨터ㆍ전화기 등(이하 “전산통신기기”)을 통하여 거래할 수 있다.</p>\r\n");
      out.write("									\r\n");
      out.write("									<p style=\"font-weight: bold; margin-bottom: 10px;\">제4조 거래방법</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 20px;\">거래처는 은행에서 내준 통장(증서· 전자통장을 포함한다) 또는 수표· 어음용지로 거래하여야 한다. 그러나 입금할 때, 자동이체약정ㆍ전산통신 기기이용약정에 따라 거래하는 경우 및 기등록된 생체정보(이하”바이오 정보”), 실명확인증표 등을 통해 본인확인된 경우에는 통장없이(이하”무통장”)도 거래할 수 있다.</p>\r\n");
      out.write("									\r\n");
      out.write("									<p style=\"font-weight: bold; margin-bottom: 10px;\">제5조 인감, 비밀번호 등의 신고</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 8px;\">① 거래처는 예금계좌를 개설할 때 인감 또는 서명, 비밀번호, 성명, 상호, 대표자명, 대리인명, 주소 등 거래에 필요한 사항을 신고하여야 한다. 다만, 비밀번호는 비밀번호 입력기(이하 “PIN-Pad기”라 한다)에 의하여 거래처가 직접 등록할 수 있으며, 거래처가 은행에 내점할 수 없는 경우 거래처는 개설된 예금의 첫거래 전에 은행이 정한 방법에 따라 전산통신기기를 이용하여 비밀번호를 등록하여야 한다.</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 8px;\">② 제 1항에 불구하고 거치식·적립식 예금은 비밀번호를 신고하지 않을 수 있다.</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 8px;\">③ 거래처는 인감과 서명을 함께 신고하거나, 인감 또는 서명을 추가 신고할 수 있다.</p>\r\n");
      out.write("									<p style=\"line-height: 1.2; margin-bottom: 20px;\">④ 통장을 발행하지 않은 경우, 은행은 거래처로부터 인감 또는 서명의 신고 절차를 생략할 수 있다.</p>\r\n");
      out.write("                  				</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"accordion accordion-flush\" id=\"faqlist2\">\r\n");
      out.write("					<div class=\"accordion-item\">\r\n");
      out.write("						 <h2 class=\"accordion-header\" id=\"headingtwo\">\r\n");
      out.write("							<label for=\"agree\">\r\n");
      out.write("							  <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq-content-2\">\r\n");
      out.write("							  <input type=\"checkbox\" name=\"agree\" value=\"1\" style =\"width: 16px; height: 15px;\">\r\n");
      out.write("							  <span style=\"font-size: 18px;\">&nbsp적립식 적금 약관</span>\r\n");
      out.write("							  </button>\r\n");
      out.write("							</label>\r\n");
      out.write("						</h2>\r\n");
      out.write("						 	<div id=\"faq-content-2\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqlist1\">\r\n");
      out.write("                  				<div class=\"accordion-body\">\r\n");
      out.write("                  				<p style=\"text-align: right; margin-bottom: 30px; font-size: 12px;\">개정준법감시인 심사필번호 제2021-약관-121호(2021.03.22)</p>\r\n");
      out.write("                  				<p style=\"text-align: center; font-size: 20px; font-weight: bold; margin-bottom: 50px;\">적립식예금약관</p>\r\n");
      out.write("                  				<p style=\"font-weight: bold; margin-bottom: 10px;\">제1조 적용범위</p>\r\n");
      out.write("                  				<p style=\"line-height: 1.2; margin-bottom: 8px;\">① 적립식예금(이하 '이 예금'이라 한다)이라 함은 기간을 정하고 그 기간중에 미리 정한 금액이나 불특정 금액을 정기 또는 부정기적으로 입금하는 예금을 말한다.</p>\r\n");
      out.write("                  				<p style=\"line-height: 1.2; margin-bottom: 20px;\">② 이 약관에서 정하지 아니한 사항은 예금거래기본약관의 규정을 적용한다.</p>\r\n");
      out.write("                  				<p style=\"font-weight: bold; margin-bottom: 10px;\">제2조 지급시기</p>\r\n");
      out.write("                  				<p style=\"line-height: 1.2; margin-bottom: 20px;\">이 예금은 약정한 만기일 이후 거래처가 청구할 때 지급한다. 다만 거래처가 부득이한 사정으로 청구할 때에는 만기전이라도 지급할 수 있다.</p>\r\n");
      out.write("                  				<p style=\"font-weight: bold; margin-bottom: 10px;\">제3조 저축금의 입금</p>\r\n");
      out.write("                  				<p style=\"line-height: 1.2; margin-bottom: 20px;\">거래처는 계약기간 동안 매월 약정한 날짜에 월저축금을 입금하여야 한다.</p>\r\n");
      out.write("                  				</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"accordion accordion-flush\" id=\"faqlist3\">\r\n");
      out.write("					<div class=\"accordion-item\">\r\n");
      out.write("						 <h2 class=\"accordion-header\" id=\"headingthree\">\r\n");
      out.write("							<label for=\"agree\">\r\n");
      out.write("							  <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq-content-3\">\r\n");
      out.write("							  <input type=\"checkbox\" name=\"agree\" value=\"1\" style =\"width: 16px; height: 15px;\">\r\n");
      out.write("							  <span style=\"font-size: 18px;\">&nbsp개인(신용)정보 수집 이용 동의서<strong style=\"font-weight: bold;\"> (필수)</strong> </span>\r\n");
      out.write("							  </button>\r\n");
      out.write("							</label>\r\n");
      out.write("						</h2>\r\n");
      out.write("						 	<div id=\"faq-content-3\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqlist1\">\r\n");
      out.write("                  				<div class=\"accordion-body\">\r\n");
      out.write("                  				<p style=\"text-align: right;\">개정준법감시인 심사필번호 제2021-약관-121호(2021.03.22)</p>\r\n");
      out.write("                  				</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"accordion accordion-flush\" id=\"faqlist4\">\r\n");
      out.write("					<div class=\"accordion-item\">\r\n");
      out.write("						 <h2 class=\"accordion-header\" id=\"headingfour\">\r\n");
      out.write("							<label for=\"agree\">\r\n");
      out.write("							  <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq-content-4\">\r\n");
      out.write("							  <input type=\"checkbox\" name=\"agree\" value=\"1\" style =\"width: 16px; height: 15px;\">\r\n");
      out.write("							  <span style=\"font-size: 18px;\">&nbsp계좌간 자동이체 약관</span>\r\n");
      out.write("							  </button>\r\n");
      out.write("							</label>\r\n");
      out.write("						</h2>\r\n");
      out.write("						 	<div id=\"faq-content-4\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqlist1\">\r\n");
      out.write("                  				<div class=\"accordion-body\">\r\n");
      out.write("                  				<p style=\"text-align: right;\">개정준법감시인 심사필번호 제2021-약관-121호(2021.03.22)</p>\r\n");
      out.write("                  				</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"accordion accordion-flush\" id=\"faqlist5\">\r\n");
      out.write("					<div class=\"accordion-item\">\r\n");
      out.write("						 <h2 class=\"accordion-header\" id=\"headingfive\">\r\n");
      out.write("							<label for=\"agree\">\r\n");
      out.write("							  <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq-content-5\">\r\n");
      out.write("							  <input type=\"checkbox\" name=\"agree\" value=\"1\" style =\"width: 16px; height: 15px;\">\r\n");
      out.write("							  <span style=\"font-size: 18px;\">&nbsp비과세종합저축특약</span>\r\n");
      out.write("							  </button>\r\n");
      out.write("							</label>\r\n");
      out.write("						</h2>\r\n");
      out.write("						 	<div id=\"faq-content-5\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqlist1\">\r\n");
      out.write("                  				<div class=\"accordion-body\">\r\n");
      out.write("                  				<p style=\"text-align: right;\">개정준법감시인 심사필번호 제2021-약관-121호(2021.03.22)</p>\r\n");
      out.write("                  				</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		    \r\n");
      out.write("		    <div class=\"text-center pt-4\" style=\"margin-top: 100px;\">\r\n");
      out.write("		    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shoppingProductJoin2\" method=\"post\">\r\n");
      out.write("		    	<input type=\"hidden\" id=\"savingCode\" name=\"savingCode\" value=\"");
      out.print(savingCode);
      out.write("\" >\r\n");
      out.write("		    	<input type=\"hidden\" id=\"interestRate\" name=\"interestRate\" value=\"");
      out.print(interestrate );
      out.write("\">\r\n");
      out.write("		    	<input type=\"hidden\" id=\"savingName\" name=\"savingName\" value=\"");
      out.print(savingName);
      out.write("\">\r\n");
      out.write("		    	<input class=\"homeBtn\" type=\"submit\" value=\"가입하기\" style=\"text-align: center; width: 150px; font-size: 18px;\" >\r\n");
      out.write("		    </form>\r\n");
      out.write("		    \r\n");
      out.write("		    \r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	const agreeChkAll = document.querySelector('input[name=agree_all]');\r\n");
      out.write("	\r\n");
      out.write("	agreeChkAll.addEventListener('change', (e) => {\r\n");
      out.write("		let agreeChk = document.querySelectorAll('input[name=agree]');\r\n");
      out.write("		for(let i = 0; i < agreeChk.length; i++){\r\n");
      out.write("		  agreeChk[i].checked = e.target.checked;\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
